package profile

// AccomplishmentType ...
type AccomplishmentType string

const (
	// AccomplishmentTypeCertificate ...
	AccomplishmentTypeCertificate AccomplishmentType = "Certificate"
	// AccomplishmentTypeLicense ...
	AccomplishmentTypeLicense AccomplishmentType = "License"
	// AccomplishmentTypeAward ...
	AccomplishmentTypeAward AccomplishmentType = "Award"
	// AccomplishmentTypeProject ...
	AccomplishmentTypeProject AccomplishmentType = "Project"
	// AccomplishmentTypePublication ...
	AccomplishmentTypePublication AccomplishmentType = "Publication"
	// AccomplishmentTypeTest ...
	AccomplishmentTypeTest AccomplishmentType = "Test"
)
