package additionaldetails

// Purpose is for additional details
type Purpose string

const (
	// PurposePromotional ...
	PurposePromotional Purpose = "promotional"
	// PurposeCorporate ...
	PurposeCorporate Purpose = "corporate"
	// PurposeRealEstate ...
	PurposeRealEstate Purpose = "real_estate"
	// PurposeTravel ...
	PurposeTravel Purpose = "travel"
	// PurposeMedical ...
	PurposeMedical Purpose = "medical"
	// PurposeAcademic ...
	PurposeAcademic Purpose = "academic"
	// PurposeEvent ...
	PurposeEvent Purpose = "event"
)
