package rental

// AdditionalFilters ...
type AdditionalFilters string

const (
	// AdditionalFiltersAny ...
	AdditionalFiltersAny AdditionalFilters = "any"
	// AdditionalFiltersElectricity ...
	AdditionalFiltersElectricity AdditionalFilters = "electricity"
	// AdditionalFiltersWater ...
	AdditionalFiltersWater AdditionalFilters = "water"
	// AdditionalFiltersNaturalGas ...
	AdditionalFiltersNaturalGas AdditionalFilters = "natural_gas"
	// AdditionalFiltersSewage ...
	AdditionalFiltersSewage AdditionalFilters = "sewage"
	// AdditionalFiltersAireConditioning ...
	AdditionalFiltersAireConditioning AdditionalFilters = "aire_conditioning"
	// AdditionalFiltersHeating ...
	AdditionalFiltersHeating AdditionalFilters = "heating"
	// AdditionalFiltersOnCorner ...
	AdditionalFiltersOnCorner AdditionalFilters = "on_corner"
	// AdditionalFiltersSmokeExtractor ...
	AdditionalFiltersSmokeExtractor AdditionalFilters = "smoke_extractor"
	// AdditionalFiltersMotoBikeGarage ...
	AdditionalFiltersMotoBikeGarage AdditionalFilters = "motobike_garage"
	// AdditionalFiltersAutomaticDoor ...
	AdditionalFiltersAutomaticDoor AdditionalFilters = "automatic_door"
	// AdditionalFiltersSecuritySystem ...
	AdditionalFiltersSecuritySystem AdditionalFilters = "security_system"
)
