package rental

// BuildingUse ...
type BuildingUse string

const (
	// BuildingUseAny ...
	BuildingUseAny BuildingUse = "any"
	// BuildingUseIndifferent ...
	BuildingUseIndifferent BuildingUse = "indifferent"
	// BuildingUseOnlyOffice ...
	BuildingUseOnlyOffice BuildingUse = "only_office"
	// BuildingUseMixed ...
	BuildingUseMixed BuildingUse = "mixed"
)
