package rental

// ClimatControl ...
type ClimatControl string

const (
	// ClimatControlAny ...
	ClimatControlAny ClimatControl = "any"
	// ClimatControlAirConditioning ...
	ClimatControlAirConditioning ClimatControl = "air_conditioning"
	// ClimatControlHearting ...
	ClimatControlHearting ClimatControl = "hearting"
	// ClimatControlWaterTank ...
	ClimatControlWaterTank ClimatControl = "water_tank"
	// ClimatControlSolarPanels ...
	ClimatControlSolarPanels ClimatControl = "solar_panels"
	// ClimatControlHighEnergyEfficiency ...
	ClimatControlHighEnergyEfficiency ClimatControl = "high_energy_efficiency"
	// ClimatControlSolarHotWater ...
	ClimatControlSolarHotWater ClimatControl = "solar_hot_water"
	// ClimatControlZonalHeating ...
	ClimatControlZonalHeating ClimatControl = "zonal_heating"
	// ClimatControlHeatPumps ...
	ClimatControlHeatPumps ClimatControl = "heat_pumps"
)
