package rental

// CommericalProperty ...
type CommericalProperty string

const (
	// CommericalPropertyAny ...
	CommericalPropertyAny CommericalProperty = "any"
	// CommericalPropertyOfficeSpace ...
	CommericalPropertyOfficeSpace CommericalProperty = "office_space"
	// CommericalPropertyCommercialPremises ...
	CommericalPropertyCommercialPremises CommericalProperty = "commercial_premises"
	// CommericalPropertyIndustrialBuilding ...
	CommericalPropertyIndustrialBuilding CommericalProperty = "industrial_building"
	// CommericalPropertyWarehouse ...
	CommericalPropertyWarehouse CommericalProperty = "warehouse"
	// CommericalPropertyFoodFacility ...
	CommericalPropertyFoodFacility CommericalProperty = "food_facility"
	// CommericalPropertyGarage ...
	CommericalPropertyGarage CommericalProperty = "garage"
	// CommericalPropertyBasement ...
	CommericalPropertyBasement CommericalProperty = "basement"
	// CommericalPropertyTradingPlace ...
	CommericalPropertyTradingPlace CommericalProperty = "trading_place"
)

// CommericalPropertyLocation ...
type CommericalPropertyLocation string

const (
	// CommericalPropertyLocationAny ...
	CommericalPropertyLocationAny CommericalPropertyLocation = "any"
	// CommericalPropertyLocationIndifferent ...
	CommericalPropertyLocationIndifferent CommericalPropertyLocation = "indifferent"
	// CommericalPropertyLocationInShoppingCentre ...
	CommericalPropertyLocationInShoppingCentre CommericalPropertyLocation = "in_shopping_centre"
	// CommericalPropertyLocationMezzanine ...
	CommericalPropertyLocationMezzanine CommericalPropertyLocation = "mezzanine"
	// CommericalPropertyLocationBelowGround ...
	CommericalPropertyLocationBelowGround CommericalPropertyLocation = "below_ground"
	// CommericalPropertyLocationOther ...
	CommericalPropertyLocationOther CommericalPropertyLocation = "other"
)
