package rental

// IndoorFeatures ...
type IndoorFeatures string

const (
	// IndoorFeaturesAny ...
	IndoorFeaturesAny IndoorFeatures = "any"
	// IndoorFeaturesEnsuit ...
	IndoorFeaturesEnsuit IndoorFeatures = "ensuit"
	// IndoorFeaturesStudy ...
	IndoorFeaturesStudy IndoorFeatures = "study"
	// IndoorFeaturesAlarmSystem ...
	IndoorFeaturesAlarmSystem IndoorFeatures = "alarm_system"
	// IndoorFeaturesFloorboards ...
	IndoorFeaturesFloorboards IndoorFeatures = "floorboards"
	// IndoorFeaturesRumpusRoom ...
	IndoorFeaturesRumpusRoom IndoorFeatures = "rumpus_room"
	// IndoorFeaturesStorageRoom ...
	IndoorFeaturesStorageRoom IndoorFeatures = "storage_room"
	// IndoorFeaturesDishwasher ...
	IndoorFeaturesDishwasher IndoorFeatures = "dishwasher"
	// IndoorFeaturesLift ...
	IndoorFeaturesLift IndoorFeatures = "lift"
	// IndoorFeaturesBuiltInRobes ...
	IndoorFeaturesBuiltInRobes IndoorFeatures = "built_in_robes"
	// IndoorFeaturesBroadband ...
	IndoorFeaturesBroadband IndoorFeatures = "broadband"
	// IndoorFeaturesGym ...
	IndoorFeaturesGym IndoorFeatures = "gym"
	// IndoorFeaturesWorkshop ...
	IndoorFeaturesWorkshop IndoorFeatures = "Workshop"
)
