package rental

// Layout ...
type Layout string

const (
	// LayoutAny ...
	LayoutAny Layout = "any"
	// LayoutIndifferent ...
	LayoutIndifferent Layout = "indifferent"
	// LayoutOpenPlan ...
	LayoutOpenPlan Layout = "open_plan"
	// LayoutWalls ...
	LayoutWalls Layout = "walls"
)
