package rental

// Material ...
type Material string

const (
	// AnyMaterial ...
	AnyMaterial Material = "any"
	// MaterialLumberComposites ...
	MaterialLumberComposites Material = "lumber_composites"
	// MaterialFencing ...
	MaterialFencing Material = "fencing"
	// MaterialDecking ...
	MaterialDecking Material = "decking"
	// MaterialFastners ...
	MaterialFastners Material = "Fastners"
	// MaterialMouldingMillwork ...
	MaterialMouldingMillwork Material = "moulding_millwork"
	// MaterialPaint ...
	MaterialPaint Material = "paint"
	// MaterialDrywall ...
	MaterialDrywall Material = "drywall"
	// MaterialDoorsWindows ...
	MaterialDoorsWindows Material = "doors_windows"
	// MaterialRoofingGutters ...
	MaterialRoofingGutters Material = "roofing_gutters"
	// MaterialLadders ...
	MaterialLadders Material = "ladders"
	// MaterialScaffolding ...
	MaterialScaffolding Material = "scaffolding"
	// MaterialPlumbing ...
	MaterialPlumbing Material = "plumbing"
	// MaterialSiding ...
	MaterialSiding Material = "siding"
	// MaterialInsulation ...
	MaterialInsulation Material = "insulation"
	// MaterialCeilings ...
	MaterialCeilings Material = "ceilings"
	// MaterialWallPaneling ...
	MaterialWallPaneling Material = "wall_paneling"
	// MaterialFlooring ...
	MaterialFlooring Material = "flooring"
	// MaterialConcreteCementMasonry ...
	MaterialConcreteCementMasonry Material = "concrete_cement_masonry"
	// MaterialMaterialHandlingEquipment ...
	MaterialMaterialHandlingEquipment Material = "material_handling_equipment"
	// MaterialBuildingHardware ...
	MaterialBuildingHardware Material = "building_hardware"
	// MaterialGlassandPlasticSheets ...
	MaterialGlassandPlasticSheets Material = "glass_and_plastic_sheets"
	// MaterialHeatingventingCooling ...
	MaterialHeatingventingCooling Material = "heating_venting_cooling"
	// MaterialOther ...
	MaterialOther Material = "other"
)
