package rental

// OutdoorFeatures ...
type OutdoorFeatures string

const (
	// OutdoorFeaturesAny ...
	OutdoorFeaturesAny OutdoorFeatures = "any"
	// OutdoorFeaturesSwimmingPool ...
	OutdoorFeaturesSwimmingPool OutdoorFeatures = "swimming_pool"
	// OutdoorFeaturesBalcony ...
	OutdoorFeaturesBalcony OutdoorFeatures = "balcony"
	// OutdoorFeaturesUndercoverParking ...
	OutdoorFeaturesUndercoverParking OutdoorFeatures = "undercover_parking"
	// OutdoorFeaturesFullyFenced ...
	OutdoorFeaturesFullyFenced OutdoorFeatures = "fully_fenced"
	// OutdoorFeaturesTennisCourt ...
	OutdoorFeaturesTennisCourt OutdoorFeatures = "tennis_court"
	// OutdoorFeaturesGarden ...
	OutdoorFeaturesGarden OutdoorFeatures = "garden"
	// OutdoorFeaturesGarage ...
	OutdoorFeaturesGarage OutdoorFeatures = "garage"
	// OutdoorFeaturesOutdoorArea ...
	OutdoorFeaturesOutdoorArea OutdoorFeatures = "outdoor_area"
	// OutdoorFeaturesShed ...
	OutdoorFeaturesShed OutdoorFeatures = "shed"
	// OutdoorFeaturesOutdoorSpa ...
	OutdoorFeaturesOutdoorSpa OutdoorFeatures = "outdoor_spa"
	// OutdoorFeaturesOutbuildings ...
	OutdoorFeaturesOutbuildings OutdoorFeatures = "out_buildings"
)
