package rental

// PostStatus ...
type PostStatus string

const (
	// PostStatusAny ...
	PostStatusAny PostStatus = "any"
	// PostStatusActive ...
	PostStatusActive PostStatus = "active"
	// PostStatusExpired ...
	PostStatusExpired PostStatus = "expired"
	// PostStatusHidden ...
	PostStatusHidden PostStatus = "hidden"
	// PostStatusSold ...
	PostStatusSold PostStatus = "sold"
)
