package rental

// PriceType ...
type PriceType string

const (
	// PriceTypeAny ...
	PriceTypeAny PriceType = "any"
	// PriceTypeTotal ...
	PriceTypeTotal PriceType = "total_price"
	// PriceTypeMetreSquare ...
	PriceTypeMetreSquare PriceType = "metre_square"
	// PriceTypeFeetSquare ...
	PriceTypeFeetSquare PriceType = "feet_square"
)
