package rental

// PropertyType ...
type PropertyType string

const (
	// PropertyTypeAll ...
	PropertyTypeAll PropertyType = "all"
	// PropertyTypeAny ...
	PropertyTypeAny PropertyType = "any"
	// PropertyTypeNewHomes ...
	PropertyTypeNewHomes PropertyType = "new_homes"
	// PropertyTypeHomes ...
	PropertyTypeHomes PropertyType = "homes"
	// PropertyTypeHouses ...
	PropertyTypeHouses PropertyType = "houses"
	// PropertyTypeAppartments ...
	PropertyTypeAppartments PropertyType = "appartments"
	// PropertyTypeGarages ...
	PropertyTypeGarages PropertyType = "garages"
	// PropertyTypeStorageRooms ...
	PropertyTypeStorageRooms PropertyType = "storage_rooms"
	// PropertyTypeOffices ...
	PropertyTypeOffices PropertyType = "offices"
	// PropertyTypeCommercialProperties ...
	PropertyTypeCommercialProperties PropertyType = "commercial_properties"
	// PropertyTypeBuildings ...
	PropertyTypeBuildings PropertyType = "buildings"
	// PropertyTypeLand ...
	PropertyTypeLand PropertyType = "land"
	// PropertyTypeBareLand ...
	PropertyTypeBareLand PropertyType = "bare_land"
	// PropertyTypeBarn ...
	PropertyTypeBarn PropertyType = "barn"
	// PropertyTypeSummerCottage ...
	PropertyTypeSummerCottage PropertyType = "summer_cottage"
	// PropertyTypeRuralFarm ...
	PropertyTypeRuralFarm PropertyType = "rural_farm"
	// PropertyTypeHotelRoom ...
	PropertyTypeHotelRoom PropertyType = "hotel_room"
)
