package rental

// Service ...
type Service string

const (
	// AnyService ...
	AnyService Service = "any"
	// ServiceAutoTransport ...
	ServiceAutoTransport Service = "auto_transport"
	// ServiceStorage ...
	ServiceStorage Service = "storage"
	// ServiceMovingSupplies ...
	ServiceMovingSupplies Service = "moving_supplies"
	// ServiceFurnitureMovers ...
	ServiceFurnitureMovers Service = "furniture_movers"
)
