package rental

// Timing ...
type Timing string

const (
	// AnyTiming ...
	AnyTiming Timing = "any"
	// TimingFlexible ...
	TimingFlexible Timing = "flexible"
	// Timing6Months ...
	Timing6Months Timing = "6_months"
	// TimingYear ...
	TimingYear Timing = "year"
)
