package rental

// TypeOfProperty ...
type TypeOfProperty string

const (
	// TypeOfPropertyAny ...
	TypeOfPropertyAny TypeOfProperty = "any"
	// TypeOfPropertyAppartaments ...
	TypeOfPropertyAppartaments TypeOfProperty = "appartaments"
	// TypeOfPropertyHouses ...
	TypeOfPropertyHouses TypeOfProperty = "houses"
	// TypeOfPropertyCountryHomes ...
	TypeOfPropertyCountryHomes TypeOfProperty = "country_homes"
	// TypeOfPropertyDuplex ...
	TypeOfPropertyDuplex TypeOfProperty = "duplex"
	// TypeOfPropertyPenthouses ...
	TypeOfPropertyPenthouses TypeOfProperty = "penthouses"
	// TypeOfPropertyBungalow ...
	TypeOfPropertyBungalow TypeOfProperty = "bungalow"
)
