package job

// ApplicantCategory ...
type ApplicantCategory string

const (
	// ApplicantCategoryNone ...
	ApplicantCategoryNone ApplicantCategory = ""
	// ApplicantCategoryFavorite ...
	ApplicantCategoryFavorite ApplicantCategory = "favorite"
	// ApplicantCategoryInReview ...
	ApplicantCategoryInReview ApplicantCategory = "in_review"
	// ApplicantCategoryDisqualified ...
	ApplicantCategoryDisqualified ApplicantCategory = "disqualified"
)
