package job

// Benefit ...
type Benefit string

const (
	// Other ...
	Other Benefit = "other"
	// LaborAgreement ...
	LaborAgreement Benefit = "labor_agreement"
	// RemoteWorking ...
	RemoteWorking Benefit = "remote_working"
	// Floater ...
	Floater Benefit = "floater"
	// PaidTimeoff ...
	PaidTimeoff Benefit = "paid_timeoff"
	// FlexibleWorkingHours ...
	FlexibleWorkingHours Benefit = "flexible_working_hours"
	// AdditionalTimeoff ...
	AdditionalTimeoff Benefit = "additional_timeoff"
	// AdditionalParentalLeave ...
	AdditionalParentalLeave Benefit = "additional_parental_leave"
	// SickLeaveForFamilyMembers ...
	SickLeaveForFamilyMembers Benefit = "sick_leave_for_family_members"
	// CompanyDaycare ...
	CompanyDaycare Benefit = "company_daycare"
	// CompanyCanteen ...
	CompanyCanteen Benefit = "company_canteen"
	// SportFacilities ...
	SportFacilities Benefit = "sport_facilities"
	// AccessForHandicappedPersons ...
	AccessForHandicappedPersons Benefit = "access_for_handicapped_persons"
	// EmployeeParking ...
	EmployeeParking Benefit = "employee_parking"
	// ShuttleService ...
	ShuttleService Benefit = "shuttle_service"
	// MultipleWorkSpaces ...
	MultipleWorkSpaces Benefit = "multiple_work_spaces"
	// CorporateEvents ...
	CorporateEvents Benefit = "corporate_events"
	// TrainigAndDevelopment ...
	TrainigAndDevelopment Benefit = "trainig_and_development"
	// PetsAllowed ...
	PetsAllowed Benefit = "pets_allowed"
	// CorporateMedicalStaff ...
	CorporateMedicalStaff Benefit = "corporate_medical_staff"
	// GameConsoles ...
	GameConsoles Benefit = "game_consoles"
	// SnackAndDrinkSelfservice ...
	SnackAndDrinkSelfservice Benefit = "snack_and_drink_selfservice"
	// PrivatePensionScheme ...
	PrivatePensionScheme Benefit = "private_pension_scheme"
	// HealthInsurance ...
	HealthInsurance Benefit = "health_insurance"
	// DentalCare ...
	DentalCare Benefit = "dental_care"
	// CarInsurance ...
	CarInsurance Benefit = "car_insurance"
	// TutionFees ...
	TutionFees Benefit = "tution_fees"
	// PermfomanceRelatedBonus ...
	PermfomanceRelatedBonus Benefit = "permfomance_related_bonus"
	// StockOptions ...
	StockOptions Benefit = "stock_options"
	// ProfitEarningBonus ...
	ProfitEarningBonus Benefit = "profit_earning_bonus"
	// AdditionalMonthsSalary ...
	AdditionalMonthsSalary Benefit = "additional_months_salary"
	// EmployersMatchingContributions ...
	EmployersMatchingContributions Benefit = "employers_matching_contributions"
	// ParentalBonus ...
	ParentalBonus Benefit = "parental_bonus"
	// TaxDeductions ...
	TaxDeductions Benefit = "tax_deductions"
	// LanguageCourses ...
	LanguageCourses Benefit = "language_courses"
	// CompanyCar ...
	CompanyCar Benefit = "company_car"
	// Laptop ...
	Laptop Benefit = "laptop"
	// DiscountsOnCompanyProductsAndServices ...
	DiscountsOnCompanyProductsAndServices Benefit = "discounts_on_company_products_and_services"
	// HolidayVouchers ...
	HolidayVouchers Benefit = "holiday_vouchers"
	// RestrauntVouchers ...
	RestrauntVouchers Benefit = "restraunt_vouchers"
	// CorporateHousing ...
	CorporateHousing Benefit = "corporate_housing"
	// MobilePhone ...
	MobilePhone Benefit = "mobile_phone"
	// GiftVouchers ...
	GiftVouchers Benefit = "gift_vouchers"
	// CulturalOrSportingActivites ...
	CulturalOrSportingActivites Benefit = "cultural_or_sporting_activites"
	// EmployeeServiceVouchers ...
	EmployeeServiceVouchers Benefit = "employee_service_vouchers"
	// CorporateCreditCard ...
	CorporateCreditCard Benefit = "corporate_credit_card"
	// RelocationPackage ...
	RelocationPackage Benefit = "relocation_package"
)
