package candidate

// ExperienceEnum ...
type ExperienceEnum string

const (
	// ExperienceEnumExpericenUnknown ...
	ExperienceEnumExpericenUnknown ExperienceEnum = "experience_unknown"
	// ExperienceEnumWithoutExperience ...
	ExperienceEnumWithoutExperience ExperienceEnum = "without_experience"
	// ExperienceEnumLessThenOneYear ...
	ExperienceEnumLessThenOneYear ExperienceEnum = "less_then_one_year"
	// ExperienceEnumOneTwoYears ...
	ExperienceEnumOneTwoYears ExperienceEnum = "one_two_years"
	// ExperienceEnumTwoThreeYears ...
	ExperienceEnumTwoThreeYears ExperienceEnum = "two_three_years"
	// ExperienceEnumThreeFiveYears ...
	ExperienceEnumThreeFiveYears ExperienceEnum = "three_five_years"
	// ExperienceEnumFiveSevenYears ...
	ExperienceEnumFiveSevenYears ExperienceEnum = "five_seven_years"
	// ExperienceEnumSevenTenYears ...
	ExperienceEnumSevenTenYears ExperienceEnum = "seven_ten_years"
	// ExperienceEnumTenYearsAndMore ...
	ExperienceEnumTenYearsAndMore ExperienceEnum = "ten_years_and_more"
)
