package group

// PrivacyType ...
type PrivacyType string

const (
	// PrivacyTypePublic ...
	PrivacyTypePublic PrivacyType = "public"
	// PrivacyTypeClosed ...
	PrivacyTypeClosed PrivacyType = "closed"
	// PrivacyTypeSecret ...
	PrivacyTypeSecret PrivacyType = "secret"
)
