package service

// OrderStatus ...
type OrderStatus string

const (
	// OrderStatusAny ...
	OrderStatusAny OrderStatus = "any"
	// OrderStatusNew ...
	OrderStatusNew OrderStatus = "new"
	// OrderStatusInProgress ...
	OrderStatusInProgress OrderStatus = "in_progress"
	// OrderStatusOutOfSchedule ...
	OrderStatusOutOfSchedule OrderStatus = "out_of_schedule"
	// OrderStatusDelivered ...
	OrderStatusDelivered OrderStatus = "delivered"
	// OrderStatusCompleted ...
	OrderStatusCompleted OrderStatus = "completed"
	// OrderStatusCanceled ...
	OrderStatusCanceled OrderStatus = "canceled"
	// OrderStatusDisputed ...
	OrderStatusDisputed OrderStatus = "disputed"
)
