package account

// Parking ...
type Parking string

const (
	// ParkingUnknown ...
	ParkingUnknown Parking = "PARKING_UNKNOWN"
	// ParkingNoParking ...
	ParkingNoParking Parking = "PARKING_NO_PARKING"
	// ParkingParkingLot ...
	ParkingParkingLot Parking = "PARKING_PARKING_LOT"
	// ParkingStreetParking ...
	ParkingStreetParking Parking = "PARKING_STREET_PARKING"
)
