variables:
  GIT_SSL_NO_VERIFY: "true"

image:
  golang:1.12.7

test:
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y )'
    - 'eval $(ssh-agent -s)'
    - 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - 'mkdir -p ~/.ssh'
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script: 
    - git config --global url."git@gitlab.lan:".insteadOf "https://gitlab.lan/"
    # - git config --global http.proxy "http://testing.lan:3128"
    # - go get -insecure -v -d ./...
    # - make
    # - go test
    # - go get github.com/opentracing/opentracing-go
    - go get -v -insecure gitlab.lan/Rightnao-site/microservices/graphql
 
  tags:
    - test
