package advert

// ActionType ...
type ActionType string

const (
	// ActionTypeImpressions ...
	ActionTypeImpressions ActionType = "impressions"
	// ActionTypeClicks ...
	ActionTypeClicks ActionType = "clicks"
	// ActionTypeForwarding ...
	ActionTypeForwarding ActionType = "forwarding"
	// ActionTypeReferals ...
	ActionTypeReferals ActionType = "referals"
)
