package advert

// Format ...
type Format string

const (
	// FormatSingleImage ...
	FormatSingleImage Format = "SINGLE_IMAGE"
	// FormatCarousel ...
	FormatCarousel Format = "CAROUSEL"
	// FormatSlide ...
	FormatSlide Format = "SLIDE"
	// FormatVideo ...
	FormatVideo Format = "VIDEO"
	// FormatImage ...
	FormatImage Format = "IMAGE"
	// FormatResponsive ...
	FormatResponsive Format = "RESPONSIVE"
	// FormatSpotlight ...
	FormatSpotlight Format = "SPOTLIGHT"
	// FormatSidePin ...
	FormatSidePin Format = "SIDE_PIN"
	// FormatHeadPin ...
	FormatHeadPin Format = "HEAD_PIN"
	// FormatBusinessSearch ...
	FormatBusinessSearch Format = "BUSINESS_SEARCH"
	// FormatProfessionalSearch ...
	FormatProfessionalSearch Format = "PROFESSIONAL_SEARCH"
	// FormatCandidatesearch ...
	FormatCandidatesearch Format = "CANDIDATE_SEARCH"
	// FormatJobsearch ...
	FormatJobsearch Format = "JOB_SEARCH"
	// FormatServiceSearch ...
	FormatServiceSearch Format = "SERVICE_SEARCH"
)
