package advert

// Type of advertisement
type Type string

const (
	// TypeAny ...
	TypeAny Type = "any"
	// TypeBanner ...
	TypeBanner Type = "banner"
	// TypeJob ...
	TypeJob Type = "job"
	// TypeCandidate ...
	TypeCandidate Type = "candidate"
	// TypeProffesional ...
	TypeProffesional Type = "professional"
	// TypeCompany ...
	TypeCompany Type = "company"
	// TypeOrganization ...
	TypeOrganization Type = "organization"
	// TypeService ...
	TypeService Type = "service"
	// TypeProduct ...
	TypeProduct Type = "product"
	// TypeRealEstate ...
	TypeRealEstate Type = "real_estate"
	// TypeAuto ...
	TypeAuto Type = "auto"
	// TypeBrand ...
	TypeBrand Type = "brand"
	// TypeShop ...
	TypeShop Type = "shop"
	// TypeOffice ...
	TypeOffice Type = "office"
)
